### ISSUE TITLE
Feedback Geral

### ISSUE THREAD

**Issue by lgnsparda** [Dinamica-dos-Fluidos-CFD/Nicolas_180036351#2]
- O relato **não está** no formato sugerido no repositório. Há muita coisa misturada. Separar no formato de modelagem, pré-processamento, e processamento e pós-processamento.
- A escrita de uma forma geral está pobre e sucinta demais. Sugere-se desenvolver melhor os pontos colocados
- Qual é o motivo do tópico "O fenômeno de Stall"?
- Qual é a utilidade do y+ para seu trabalho?
- A descrição das escolhas do pré-processamento está desorganizada e com escrita pobre. Sugere-se refazer esta parte!
- As figuras do tópico "Convergência" não são curvas de convergência!
- Porque você considerou que 15% de diferença no cálculo do arrasto é "grande imprecisão"?
- No tópico "Análise paramétrica: α=30°", como você determinou na simulação que está em *stall*?
- De uma forma geral, nota-se que o relato no repositório foi feito às pressas, o que pode indicar que foi deixado para a última hora. Muita coisa precisa ser refeita aqui!

**Comment by NicolasNemer** [comment]
De uma forma geral, nota-se que o relato no repositório foi feito às pressas, o que pode indicar que foi deixado para a última hora. Muita coisa precisa ser refeita aqui! - infelizmente, passei a semana inteira tentando resolver problemas no meu computador, problemas com a minha internet e com o software do ansys. Infelizmente perdi MUITO tempo com isso. Só consegui resolver na quinta feira a noite, para assim, prosseguir com a minha simulação enfim escrever o repositório.

**Comment by NicolasNemer** [comment]
A escrita de uma forma geral está pobre e sucinta demais. - Devido ao limite de palavras no relatório para o SAE aerodesing, desenvolvi essa hábito de escrever de forma concisa. Meu objetivo é apresentar a informação com o mínimo de palavras possível. Usando palavras simples.

**Comment by NicolasNemer** [comment]
Qual é o motivo do tópico "O fenômeno de Stall"? removi esse tópio e complementei a análise de stall no pós-processamento

**Comment by NicolasNemer** [comment]
Qual é a utilidade do y+ para seu trabalho? removi

**Comment by NicolasNemer** [comment]
A descrição das escolhas do pré-processamento está desorganizada e com escrita pobre. Sugere-se refazer esta parte! - refeito, por favor, comente o que achou. creio que não houve muita melhora infelizmente

**Comment by NicolasNemer** [comment]
Porque você considerou que 15% de diferença no cálculo do arrasto é "grande imprecisão"? - pois é 3 vezes a tolerância definia na modelagem. Entretando a expressão foi mesmo exagerada. Mudei o texto

**Comment by NicolasNemer** [comment]
No tópico "Análise paramétrica: α=30°", como você determinou na simulação que está em stall? - Mudei o texto . fiz uma análisa mais crua

**Comment by NicolasNemer** [comment]
As figuras do tópico "Convergência" não são curvas de convergência! - mudei isto

**Comment by lgnsparda** [comment]
- Há erros grosseiros de digitação no texto
- No tópico "Domínio e Geometria" há a descrição do y+ da malha. Qual é a motivação em mencionar esta grandeza?
- As imagens do site da NASA não estão referenciadas!
- Evitar usar termos em inglês no texto quando possível. Priorizar o uso da língua portuguesa.
- Colocar referências bibliográficas
